### ISSUE TITLE
Formatting Broken on Windows 11 with Chrome 101.0.4951.67 

### ISSUE THREAD

**Issue by kickofline** [vampyre420/vampyre420.github.io#2]
![image](https://user-images.githubusercontent.com/31192414/169867430-fede737c-f754-490c-8742-f8ef8584b10c.png)
![image](https://user-images.githubusercontent.com/31192414/169867576-58507d31-51ed-4e08-be9c-200e771ee9a2.png)
![image](https://user-images.githubusercontent.com/31192414/169867620-daa9d11c-b3c2-4b81-8752-23a6106b325f.png)
![image](https://user-images.githubusercontent.com/31192414/169867637-60c12e15-8207-4e5c-8381-2cd241c6abc8.png)

**Comment by vampyre420** [comment]
As it stands, there are a lot of formatting issues across different devices, screen sizes and browsers.  This website is still in the alpha phase, and due to that fact the website may be buggy or not work at all.  This is especially prevalent on mobile platforms.  However, I appreciate any and all bug reports, which is why when this website reaches beta, bug reports will be a feature of the website.

**Comment by kickofline** [comment]
you are a poopy head
